### ISSUE TITLE
Openbox renders base Numix window manager theme for each profile [bug]

### ISSUE THREAD

**Issue by treymerkley** [Ferdi265/numix-solarized-gtk-theme#18] opened 2018-02-09 07:21 UTC
I just started using Openbox, and the window manager themes render out as the base Numix theme without any of the solarized parts. 

I ran the PKGBUILD after the last pull request, so it should run if it was going to, but I can also run it under OB to see what happens.

**Comment by Ferdi265** [comment] 2018-02-10 14:10
The WM themes aren't made to look solarized yet, I didn't really have time to install all those WMs and test them, and find matching colors. The corresponding folder is `src/openbox-3`.

If you want you can try adding some matching colors to the WM themes.

This issue is a duplicate of #1 (Numix WM themes not updated to Solarized Colors), closing. Further discussion please in the main issue.

**Closed as completed by Ferdi265** 2018-02-10 14:10 UTC
